/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodGroup = IDL.Variant({
  'aNegative' : IDL.Null,
  'oPositive' : IDL.Null,
  'abPositive' : IDL.Null,
  'bPositive' : IDL.Null,
  'aPositive' : IDL.Null,
  'oNegative' : IDL.Null,
  'abNegative' : IDL.Null,
  'bNegative' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const ActiveLocation = IDL.Record({
  'requestId' : IDL.Opt(IDL.Text),
  'requester' : IDL.Opt(IDL.Principal),
  'urgency' : IDL.Opt(
    IDL.Variant({
      'normal' : IDL.Null,
      'high' : IDL.Null,
      'critical' : IDL.Null,
    })
  ),
  'type' : IDL.Variant({ 'request' : IDL.Null, 'donor' : IDL.Null }),
  'availability' : IDL.Opt(IDL.Bool),
  'bloodGroup' : BloodGroup,
  'coordinates' : IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  }),
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'contactPref' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'available' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'location' : Location,
});
export const Time = IDL.Int;
export const BloodRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'matched' : IDL.Null,
  }),
  'requester' : IDL.Principal,
  'urgency' : IDL.Variant({
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
  }),
  'createdAt' : Time,
  'bloodGroup' : BloodGroup,
  'matchedDonor' : IDL.Opt(IDL.Principal),
  'location' : Location,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createBloodRequest' : IDL.Func(
      [
        BloodGroup,
        Location,
        IDL.Variant({
          'normal' : IDL.Null,
          'high' : IDL.Null,
          'critical' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'findDonorsForBloodGroup' : IDL.Func(
      [BloodGroup],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getActiveLocations' : IDL.Func([], [IDL.Vec(ActiveLocation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getRequestsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BloodRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBloodRequestStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'matched' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodGroup = IDL.Variant({
    'aNegative' : IDL.Null,
    'oPositive' : IDL.Null,
    'abPositive' : IDL.Null,
    'bPositive' : IDL.Null,
    'aPositive' : IDL.Null,
    'oNegative' : IDL.Null,
    'abNegative' : IDL.Null,
    'bNegative' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const ActiveLocation = IDL.Record({
    'requestId' : IDL.Opt(IDL.Text),
    'requester' : IDL.Opt(IDL.Principal),
    'urgency' : IDL.Opt(
      IDL.Variant({
        'normal' : IDL.Null,
        'high' : IDL.Null,
        'critical' : IDL.Null,
      })
    ),
    'type' : IDL.Variant({ 'request' : IDL.Null, 'donor' : IDL.Null }),
    'availability' : IDL.Opt(IDL.Bool),
    'bloodGroup' : BloodGroup,
    'coordinates' : IDL.Record({
      'latitude' : IDL.Float64,
      'longitude' : IDL.Float64,
    }),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'contactPref' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'available' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'location' : Location,
  });
  const Time = IDL.Int;
  const BloodRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'matched' : IDL.Null,
    }),
    'requester' : IDL.Principal,
    'urgency' : IDL.Variant({
      'normal' : IDL.Null,
      'high' : IDL.Null,
      'critical' : IDL.Null,
    }),
    'createdAt' : Time,
    'bloodGroup' : BloodGroup,
    'matchedDonor' : IDL.Opt(IDL.Principal),
    'location' : Location,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createBloodRequest' : IDL.Func(
        [
          BloodGroup,
          Location,
          IDL.Variant({
            'normal' : IDL.Null,
            'high' : IDL.Null,
            'critical' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'findDonorsForBloodGroup' : IDL.Func(
        [BloodGroup],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getActiveLocations' : IDL.Func([], [IDL.Vec(ActiveLocation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getRequestsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BloodRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBloodRequestStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'matched' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };