/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveLocation {
  'requestId' : [] | [string],
  'requester' : [] | [Principal],
  'urgency' : [] | [
    { 'normal' : null } |
      { 'high' : null } |
      { 'critical' : null }
  ],
  'type' : { 'request' : null } |
    { 'donor' : null },
  'availability' : [] | [boolean],
  'bloodGroup' : BloodGroup,
  'coordinates' : { 'latitude' : number, 'longitude' : number },
}
export type BloodGroup = { 'aNegative' : null } |
  { 'oPositive' : null } |
  { 'abPositive' : null } |
  { 'bPositive' : null } |
  { 'aPositive' : null } |
  { 'oNegative' : null } |
  { 'abNegative' : null } |
  { 'bNegative' : null };
export interface BloodRequest {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null } |
    { 'matched' : null },
  'requester' : Principal,
  'urgency' : { 'normal' : null } |
    { 'high' : null } |
    { 'critical' : null },
  'createdAt' : Time,
  'bloodGroup' : BloodGroup,
  'matchedDonor' : [] | [Principal],
  'location' : Location,
}
export interface Location {
  'latitude' : number,
  'city' : string,
  'longitude' : number,
  'address' : string,
}
export type Time = bigint;
export interface UserProfile {
  'contactPref' : string,
  'name' : string,
  'role' : UserRole,
  'available' : boolean,
  'bloodGroup' : BloodGroup,
  'location' : Location,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createBloodRequest' : ActorMethod<
    [
      BloodGroup,
      Location,
      { 'normal' : null } |
        { 'high' : null } |
        { 'critical' : null },
    ],
    string
  >,
  'findDonorsForBloodGroup' : ActorMethod<[BloodGroup], Array<Principal>>,
  'getActiveLocations' : ActorMethod<[], Array<ActiveLocation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getRequestsForUser' : ActorMethod<[Principal], Array<BloodRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBloodRequestStatus' : ActorMethod<
    [
      string,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'completed' : null } |
        { 'matched' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];