/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    city: string;
    longitude: number;
    address: string;
}
export type Time = bigint;
export interface ActiveLocation {
    requestId?: string;
    requester?: Principal;
    urgency?: Variant_normal_high_critical;
    type: Variant_request_donor;
    availability?: boolean;
    bloodGroup: BloodGroup;
    coordinates: {
        latitude: number;
        longitude: number;
    };
}
export interface UserProfile {
    contactPref: string;
    name: string;
    role: UserRole;
    available: boolean;
    bloodGroup: BloodGroup;
    location: Location;
}
export interface BloodRequest {
    id: string;
    status: Variant_cancelled_pending_completed_matched;
    requester: Principal;
    urgency: Variant_normal_high_critical;
    createdAt: Time;
    bloodGroup: BloodGroup;
    matchedDonor?: Principal;
    location: Location;
}
export enum BloodGroup {
    aNegative = "aNegative",
    oPositive = "oPositive",
    abPositive = "abPositive",
    bPositive = "bPositive",
    aPositive = "aPositive",
    oNegative = "oNegative",
    abNegative = "abNegative",
    bNegative = "bNegative"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_completed_matched {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    matched = "matched"
}
export enum Variant_normal_high_critical {
    normal = "normal",
    high = "high",
    critical = "critical"
}
export enum Variant_request_donor {
    request = "request",
    donor = "donor"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createBloodRequest(bloodGroup: BloodGroup, location: Location, urgency: Variant_normal_high_critical): Promise<string>;
    findDonorsForBloodGroup(bloodGroup: BloodGroup): Promise<Array<Principal>>;
    getActiveLocations(): Promise<Array<ActiveLocation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getRequestsForUser(user: Principal): Promise<Array<BloodRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBloodRequestStatus(requestId: string, status: Variant_cancelled_pending_completed_matched): Promise<void>;
}
import type { ActiveLocation as _ActiveLocation, BloodGroup as _BloodGroup, BloodRequest as _BloodRequest, Location as _Location, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBloodRequest(arg0: BloodGroup, arg1: Location, arg2: Variant_normal_high_critical): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBloodRequest(to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBloodRequest(to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async findDonorsForBloodGroup(arg0: BloodGroup): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.findDonorsForBloodGroup(to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findDonorsForBloodGroup(to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveLocations(): Promise<Array<ActiveLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLocations();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLocations();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsForUser(arg0: Principal): Promise<Array<BloodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsForUser(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsForUser(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBloodRequestStatus(arg0: string, arg1: Variant_cancelled_pending_completed_matched): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBloodRequestStatus(arg0, to_candid_variant_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBloodRequestStatus(arg0, to_candid_variant_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActiveLocation_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveLocation): ActiveLocation {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BloodGroup_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BloodRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequest): BloodRequest {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        normal: null;
    } | {
        high: null;
    } | {
        critical: null;
    }]): Variant_normal_high_critical | null {
    return value.length === 0 ? null : from_candid_variant_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactPref: string;
    name: string;
    role: _UserRole;
    available: boolean;
    bloodGroup: _BloodGroup;
    location: _Location;
}): {
    contactPref: string;
    name: string;
    role: UserRole;
    available: boolean;
    bloodGroup: BloodGroup;
    location: Location;
} {
    return {
        contactPref: value.contactPref,
        name: value.name,
        role: from_candid_UserRole_n20(_uploadFile, _downloadFile, value.role),
        available: value.available,
        bloodGroup: from_candid_BloodGroup_n15(_uploadFile, _downloadFile, value.bloodGroup),
        location: value.location
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    } | {
        matched: null;
    };
    requester: Principal;
    urgency: {
        normal: null;
    } | {
        high: null;
    } | {
        critical: null;
    };
    createdAt: _Time;
    bloodGroup: _BloodGroup;
    matchedDonor: [] | [Principal];
    location: _Location;
}): {
    id: string;
    status: Variant_cancelled_pending_completed_matched;
    requester: Principal;
    urgency: Variant_normal_high_critical;
    createdAt: Time;
    bloodGroup: BloodGroup;
    matchedDonor?: Principal;
    location: Location;
} {
    return {
        id: value.id,
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        urgency: from_candid_variant_n12(_uploadFile, _downloadFile, value.urgency),
        createdAt: value.createdAt,
        bloodGroup: from_candid_BloodGroup_n15(_uploadFile, _downloadFile, value.bloodGroup),
        matchedDonor: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.matchedDonor)),
        location: value.location
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requestId: [] | [string];
    requester: [] | [Principal];
    urgency: [] | [{
            normal: null;
        } | {
            high: null;
        } | {
            critical: null;
        }];
    type: {
        request: null;
    } | {
        donor: null;
    };
    availability: [] | [boolean];
    bloodGroup: _BloodGroup;
    coordinates: {
        latitude: number;
        longitude: number;
    };
}): {
    requestId?: string;
    requester?: Principal;
    urgency?: Variant_normal_high_critical;
    type: Variant_request_donor;
    availability?: boolean;
    bloodGroup: BloodGroup;
    coordinates: {
        latitude: number;
        longitude: number;
    };
} {
    return {
        requestId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.requestId)),
        requester: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.requester)),
        urgency: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.urgency)),
        type: from_candid_variant_n13(_uploadFile, _downloadFile, value.type),
        availability: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.availability)),
        bloodGroup: from_candid_BloodGroup_n15(_uploadFile, _downloadFile, value.bloodGroup),
        coordinates: value.coordinates
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    high: null;
} | {
    critical: null;
}): Variant_normal_high_critical {
    return "normal" in value ? Variant_normal_high_critical.normal : "high" in value ? Variant_normal_high_critical.high : "critical" in value ? Variant_normal_high_critical.critical : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: null;
} | {
    donor: null;
}): Variant_request_donor {
    return "request" in value ? Variant_request_donor.request : "donor" in value ? Variant_request_donor.donor : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
}): BloodGroup {
    return "aNegative" in value ? BloodGroup.aNegative : "oPositive" in value ? BloodGroup.oPositive : "abPositive" in value ? BloodGroup.abPositive : "bPositive" in value ? BloodGroup.bPositive : "aPositive" in value ? BloodGroup.aPositive : "oNegative" in value ? BloodGroup.oNegative : "abNegative" in value ? BloodGroup.abNegative : "bNegative" in value ? BloodGroup.bNegative : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    matched: null;
}): Variant_cancelled_pending_completed_matched {
    return "cancelled" in value ? Variant_cancelled_pending_completed_matched.cancelled : "pending" in value ? Variant_cancelled_pending_completed_matched.pending : "completed" in value ? Variant_cancelled_pending_completed_matched.completed : "matched" in value ? Variant_cancelled_pending_completed_matched.matched : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodRequest>): Array<BloodRequest> {
    return value.map((x)=>from_candid_BloodRequest_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActiveLocation>): Array<ActiveLocation> {
    return value.map((x)=>from_candid_ActiveLocation_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactPref: string;
    name: string;
    role: UserRole;
    available: boolean;
    bloodGroup: BloodGroup;
    location: Location;
}): {
    contactPref: string;
    name: string;
    role: _UserRole;
    available: boolean;
    bloodGroup: _BloodGroup;
    location: _Location;
} {
    return {
        contactPref: value.contactPref,
        name: value.name,
        role: to_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        available: value.available,
        bloodGroup: to_candid_BloodGroup_n3(_uploadFile, _downloadFile, value.bloodGroup),
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_completed_matched): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    matched: null;
} {
    return value == Variant_cancelled_pending_completed_matched.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_completed_matched.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_completed_matched.completed ? {
        completed: null
    } : value == Variant_cancelled_pending_completed_matched.matched ? {
        matched: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
} {
    return value == BloodGroup.aNegative ? {
        aNegative: null
    } : value == BloodGroup.oPositive ? {
        oPositive: null
    } : value == BloodGroup.abPositive ? {
        abPositive: null
    } : value == BloodGroup.bPositive ? {
        bPositive: null
    } : value == BloodGroup.aPositive ? {
        aPositive: null
    } : value == BloodGroup.oNegative ? {
        oNegative: null
    } : value == BloodGroup.abNegative ? {
        abNegative: null
    } : value == BloodGroup.bNegative ? {
        bNegative: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_normal_high_critical): {
    normal: null;
} | {
    high: null;
} | {
    critical: null;
} {
    return value == Variant_normal_high_critical.normal ? {
        normal: null
    } : value == Variant_normal_high_critical.high ? {
        high: null
    } : value == Variant_normal_high_critical.critical ? {
        critical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
